name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Prepare Workplace
      run: make clean
      
    - name: Run tests
      run: make test
      
    - name: Compile output
      run: make
